export const GET_ALL_FAMILY_MEMBERS = 'GET_ALL_FAMILY_MEMBERS';
export const GET_ALL_FAMILY_MEMBERS_REQUEST = 'GET_ALL_FAMILY_MEMBERS_REQUEST';
export const GET_ALL_FAMILY_MEMBERS_SUCCESS = 'GET_ALL_FAMILY_MEMBERS_SUCCESS';
export const GET_ALL_FAMILY_MEMBERS_FAILURE = 'GET_ALL_FAMILY_MEMBERS_FAILURE';
export const GET_FAMILY_MEMBER_BY_ID = 'GET_FAMILY_MEMBER_BY_ID';
export const DELETE_FAMILY_MEMBER_REQUEST = 'DELETE_FAMILY_MEMBER_REQUEST';
export const DELETE_FAMILY_MEMBER_SUCCESS = 'DELETE_FAMILY_MEMBER_SUCCESS';
export const DELETE_FAMILY_MEMBER_FAILURE = 'DELETE_FAMILY_MEMBER_FAILURE';