export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_REQUEST = 'GET_ALL_QUESTIONS_REQUEST';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_FAILURE = 'GET_ALL_QUESTIONS_FAILURE';
export const POST_NEW_QUESTION = 'POST_NEW_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION'; 