export const GET_ALL_ARTIFACTS = 'GET_ALL_ARTIFACTS';
export const GET_ALL_ARTIFACTS_REQUEST = 'GET_ALL_ARTIFACTS_REQUEST';
export const GET_ALL_ARTIFACTS_SUCCESS = 'GET_ALL_ARTIFACTS_SUCCESS';
export const GET_ALL_ARTIFACTS_FAILURE = 'GET_ALL_ARTIFACTS_FAILURE';
export const GET_ARTIFACT_BY_ID = 'GET_ARTIFACT_BY_ID';

