export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL'; 
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL'; 
export const OPEN_ADD_MEMBER_MODAL = 'OPEN_ADD_MEMBER_MODAL';
export const CLOSE_ADD_MEMBER_MODAL = 'CLOSE_ADD_MEMBER_MODAL';