export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_EVENTS_REQUEST = 'GET_ALL_EVENTS_REQUEST';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const GET_ALL_EVENTS_FAILURE = 'GET_ALL_EVENTS_FAILURE';
export const GET_TIMELINE_EVENT_BY_ID = 'GET_TIMELINE_EVENT_BY_ID';
export const CREATE_TIMELINE_EVENT = 'CREATE_TIMELINE_EVENT';