export const familyMembers = [
  {
    id: 1,
    firstName: "Helen",
    middleName: "French",
    lastName: "Rogers",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 16,
    birthMonth: 12,
    birthYear: 1920,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    bioParagraph1: null,
    bioParagraph2: null,
    bioParagraph3: null,
    bioParagraph4: null,
    bioParagraph5: null,
    bioParagraph6: null,
    bioParagraph7: null,
    birthplace: "Iuka, MS",
    residence: "Gary, IN",
    isAlive: true,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 2,
    userId: null 
  },
  {
    id: 2,
    firstName: "Oscar",
    middleName: null,
    lastName: "Rogers",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: 1994,
    birthplace: null,
    residence: null,
    isAlive: false,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 1,
    userId: null 
  },
  {
    id: 3,
    firstName: "Patricia",
    middleName: null,
    lastName: "Crozier",
    preferredName: "Pat",
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 4,
    birthMonth: 7,
    birthYear: 1941,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: 1,
    secondaryParentId: 2,
    isActiveUser: false,
    spouseId: 4,
    userId: null 
  },
  {
    id: 4,
    firstName: "Ronald",
    middleName: null,
    lastName: "Crozier",
    preferredName: null,
    suffix: "Sr.",
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: 2012,
    birthplace: null,
    residence: null,
    isAlive: false,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 3,
    userId: null 
  },
  {
    id: 5,
    firstName: "Rogercarole",
    middleName: null,
    lastName: "Rogers",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 13,
    birthMonth: 4,
    birthYear: 1948,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: 1,
    secondaryParentId: 2,
    isActiveUser: false,
    spouseId: 6,
    userId: null 
  },
  {
    id: 6,
    firstName: "Robert",
    middleName: null,
    lastName: "Hall",
    preferredName: "Bobby",
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: 1,
    deathYear: 2018,
    birthplace: null,
    residence: null,
    isAlive: false,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 5,
    userId: null 
  },
  {
    id: 7,
    firstName: "Oscar",
    middleName: "Barry",
    lastName: "Rogers",
    preferredName: "Barry",
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 11,
    birthMonth: 6,
    birthYear: 1952,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: false,
    primaryParentId: 1,
    secondaryParentId: 2,
    isActiveUser: false,
    spouseId: null,
    userId: null 
  },
  {
    id: 8,
    firstName: "Angela",
    middleName: null,
    lastName: "Peasant",
    preferredName: "Angie",
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: 3,
    secondaryParentId: 4,
    isActiveUser: false,
    spouseId: 9,
    userId: null 
  },
  {
    id: 9,
    firstName: "Walter",
    middleName: null,
    lastName: "Peasant",
    preferredName: null,
    suffix: "Sr.",
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 8,
    userId: null 
  },
  {
    id: 10,
    firstName: "Adella",
    middleName: null,
    lastName: "Crozier",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 17,
    birthMonth: 1,
    birthYear: 1966,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: "Gary, IN",
    residence: "Detroit, MI",
    isAlive: true,
    hasSpouse: true,
    primaryParentId: 3,
    secondaryParentId: 4,
    isActiveUser: false,
    spouseId: 11,
    userId: null 
  },
  {
    id: 11,
    firstName: "Nikita",
    middleName: null,
    lastName: "Crozier",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 10,
    userId: null 
  },
  {
    id: 12,
    firstName: "Ronald",
    middleName: null,
    lastName: "Crozier",
    preferredName: "Ronnie",
    suffix: "Jr.",
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: 3,
    secondaryParentId: 4,
    isActiveUser: false,
    spouseId: 13,
    userId: null 
  },
  {
    id: 13,
    firstName: "LeToia",
    middleName: null,
    lastName: "Crozier",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 12,
    userId: null 
  },
  {
    id: 14,
    firstName: "Simone",
    middleName: "French",
    lastName: "Banks",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 27,
    birthMonth: 11,
    birthYear: 1987,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: 5,
    secondaryParentId: 6,
    isActiveUser: false,
    spouseId: 15,
    userId: null 
  },
  {
    id: 15,
    firstName: "Christopher",
    middleName: null,
    lastName: "Banks",
    preferredName: "Chris",
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: true,
    primaryParentId: null,
    secondaryParentId: null,
    isActiveUser: false,
    spouseId: 14,
    userId: null 
  },
  {
    id: 16,
    firstName: "Barry",
    middleName: "Alexandre",
    lastName: "Rogers",
    preferredName: "Alex",
    suffix: null,
    profilePhotoUrl: null,
    birthDay: 23,
    birthMonth: 8,
    birthYear: 1994,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    bioParagraph1: "something interesting",
    bioParagraph2: "something more interesting",
    bioParagraph3: "i am a walrus",
    bioParagraph4: null,
    bioParagraph5: null,
    bioParagraph6: null,
    bioParagraph7: null,
    birthplace: "Minneapolis, MN",
    residence: "Atlanta, GA",
    isAlive: true,
    hasSpouse: false,
    primaryParentId: 7,
    secondaryParentId: null,
    isActiveUser: true,
    spouseId: null,
    userId: 101 
  },
  {
    id: 17,
    firstName: "Ashley",
    middleName: "Noel",
    lastName: "Peasant",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: false,
    primaryParentId: 8,
    secondaryParentId: 9,
    isActiveUser: false,
    spouseId: null,
    userId: null 
  },
  {
    id: 18,
    firstName: "Walter",
    middleName: null,
    lastName: "Peasant",
    preferredName: "Tony",
    suffix: "Jr.",
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: false,
    primaryParentId: 8,
    secondaryParentId: 9,
    isActiveUser: false,
    spouseId: null,
    userId: null 
  },
  {
    id: 19,
    firstName: "Yori",
    middleName: null,
    lastName: "Crozier",
    preferredName: null,
    suffix: null,
    profilePhotoUrl: null,
    birthDay: null,
    birthMonth: null,
    birthYear: null,
    deathDay: null,
    deathMonth: null,
    deathYear: null,
    birthplace: null,
    residence: null,
    isAlive: true,
    hasSpouse: false,
    primaryParentId: 12,
    secondaryParentId: 13,
    isActiveUser: false,
    spouseId: null,
    userId: null 
  }
];
